zookeeper:
  image: dehora/zookeeper
  ports:
    - 2181:2181

kafka:
  image: dehora/kafka
  links:
    - zookeeper:zookeeper
  ports:
    - 9092:9092

schema-registry:
  image: dehora/schema-registry
  links:
    - zookeeper:zookeeper
    - kafka
  ports:
    - 8081:8081

rest-proxy:
  image: dehora/rest-proxy
  links:
    - zookeeper:zookeeper
    - kafka
    - schema-registry
  ports:
    - 8082:8082

tools:
  image: dehora/tools
  links:
    - zookeeper:zookeeper
    - kafka
    - schema-registry
